
services:
  mongodb:
    container_name: mongo_db
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    env_file:
      - .env
    command: [--auth]
